[package]
name = "bucky-time"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/buckyos/bucky-time.git"
license-file = "LISCENSE"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
